name: CI (Coq)

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        env:
        - { COQ_VERSION: "8.7.1" , COQ_PACKAGE: "coq-8.7.1 libcoq-8.7.1-ocaml-dev"  , PPA: "ppa:jgross-h/many-coq-versions" }

    env: ${{ matrix.env }}

    steps:
    - name: install Coq
      run: |
        sudo add-apt-repository "$PPA" -y
        sudo apt-get -o Acquire::Retries=30 update -q
        sudo apt-get -o Acquire::Retries=30 install camlp5 $COQ_PACKAGE -y --allow-unauthenticated
    - name: echo build params
      run: |
        echo "::group::lscpu"
        lscpu
        echo "::endgroup::"
        echo "::group::uname -a"
        uname -a
        echo "::endgroup::"
        echo "::group::lsb_release -a"
        lsb_release -a
        echo "::endgroup::"
        echo "::group::ghc --version"
        ghc --version
        echo "::endgroup::"
        echo "::group::gcc -v"
        gcc -v
        echo "::endgroup::"
        echo "::group::ocamlc -config"
        ocamlc -config
        echo "::endgroup::"
        echo "::group::coqc --config"
        coqc --config
        echo "::endgroup::"
        echo "::group::coqc --version"
        coqc --version
        echo "::endgroup::"
        echo "::group::echo | coqtop"
        echo | coqtop
        echo "::endgroup::"
    - uses: actions/checkout@v2
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
    - name: clone deps
      run: |
        git clone https://github.com/ppedrot/ltac2.git && (cd ltac2 && git checkout d0591d12344adeaff7f51dc56f38ebcda7ba7c7c)
        git clone https://github.com/unicoq/unicoq.git && (cd unicoq && git checkout fd5f41f32f5f7cb94de81d66a42dff18df7084a2)
        git clone https://github.com/Mtac2/Mtac2.git && (cd Mtac2 && git checkout 607689192296bc42d75bc933ab2229a6b347c73b)
        git clone https://github.com/Template-Coq/template-coq.git && (cd template-coq && git checkout d6f621d27e882f16cf555d78b3e587038951ea94)
    - name: install Ltac2
      run: |
        (cd ltac2 && make && sudo make install)
    - name: install UniCoq
      run: |
        (cd unicoq && coq_makefile -f Make -o Makefile && make && sudo make install)
    - name: install Mtac2
      run: |
        (cd Mtac2 && coq_makefile -f _CoqProject -o Makefile && make && sudo make install)
    - name: install Template-Coq
      run: |
        (cd template-coq && make && sudo make install)
    - run: make -j2
