name: CI (Coq)

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        env:
        - { COQ_VERSION: "8.12.2", COQ_PACKAGE: "coq-8.12.2 libcoq-8.12.2-ocaml-dev", PPA: "ppa:jgross-h/many-coq-versions-ocaml-4-05" }

    env: ${{ matrix.env }}

    steps:
    - name: install Coq
      run: |
        sudo add-apt-repository "$PPA" -y
        sudo apt-get -o Acquire::Retries=30 update -q
        sudo apt-get -o Acquire::Retries=30 install $COQ_PACKAGE -y --allow-unauthenticated
    - name: echo build params
      run: |
        echo "::group::lscpu"
        lscpu
        echo "::endgroup::"
        echo "::group::uname -a"
        uname -a
        echo "::endgroup::"
        echo "::group::lsb_release -a"
        lsb_release -a
        echo "::endgroup::"
        echo "::group::ghc --version"
        ghc --version
        echo "::endgroup::"
        echo "::group::gcc -v"
        gcc -v
        echo "::endgroup::"
        echo "::group::ocamlc -config"
        ocamlc -config
        echo "::endgroup::"
        echo "::group::coqc --config"
        coqc --config
        echo "::endgroup::"
        echo "::group::coqc --version"
        coqc --version
        echo "::endgroup::"
        echo "::group::echo | coqtop"
        echo | coqtop
        echo "::endgroup::"
    - uses: actions/checkout@v2
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
    - name: clone deps
      run: |
        git clone https://github.com/unicoq/unicoq.git && (cd unicoq && git checkout e1c991b09767887676d07feb2054e4db321216cb)
        git clone https://github.com/Mtac2/Mtac2.git && (cd Mtac2 && git checkout 653c3a04cfad0adf8fd287cc1fa4e8b9a0be1a34)
        git clone https://github.com/mattam82/Coq-Equations.git && (cd Coq-Equations && git checkout 837011076e07a8de7e47576e04a6b99fabdab6ad)
        git clone https://github.com/MetaCoq/metacoq.git && (cd metacoq && git checkout 753ac0ba4817b9506ad5cae3aefff1a2f71dd055)
    - name: install UniCoq
      run: |
        (cd unicoq && coq_makefile -f _CoqProject -o Makefile && make && sudo make install)
    - name: install Mtac2
      run: |
        (cd Mtac2 && coq_makefile -f _CoqProject -o Makefile && make && sudo make install)
    - name: install Coq-Equations
      run: |
        (cd Coq-Equations && ./configure.sh && make && sudo make install)
    - name: install Template-Coq
      run: |
        (cd metacoq && ./configure.sh && make template-coq && sudo make -C template-coq install)
    - run: make -j2
